services:
    client:
        build:
            context: ./client
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        environment:
            - CHOKIDAR_USEPOLLING=true
        depends_on:
            - backend
        networks:
            - app-network

    server:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '5000:5000'
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
